// Biomarker 정제(cleaning) + 정규화(normalization) — dataSource 로드 시 1회 적용.
// 목적: (1) genomic/biomarker/ctDNA/CDx 등 '바이오마커 아님' 제거,
//       (2) MSI-H/MSI/microsatellite instability, ERBB2/HER2, "EGFR mutation"/EGFR 등 표기 병합.
// 원칙: 정확 일치(소문자+공백정규화 키). KRAS G12C·BRAF V600E·HER2-low 등 임상적으로 구별되는
//       변이/상태는 보존(과병합 금지). 이 파일은 scripts/build_biomarker_map.py 로 데이터서 생성 — 직접 수정 금지.

const norm = (s) => (s || '').trim().replace(/\s+/g, ' ').toLowerCase()

// 제거: generic 용어·방법·카테고리·임상상태·핵산 analyte(액체생검)
const BLOCK = new Set([
  "amplification",
  "assay",
  "biomarker",
  "biomarker analysis",
  "biomarker negative",
  "biomarker positive",
  "biomarker status",
  "biomarkers",
  "ccfdna",
  "cdna",
  "cdx",
  "cell-free dna",
  "cfdna",
  "cfdna methylation",
  "circulating tumor cell",
  "circulating tumor cells",
  "circulating tumor dna",
  "clinical stage",
  "cnv",
  "cnvs",
  "companion diagnostic",
  "copy number",
  "copy number alteration",
  "copy number alterations",
  "copy number variation",
  "ct-dna",
  "ct-hpv dna",
  "ctc",
  "ctcna",
  "ctcs",
  "ctdna",
  "ctdna methylation",
  "cthpvdna",
  "ddpcr",
  "deletion",
  "dna",
  "dna damage response",
  "dna damage response (ddr)",
  "dna methylation",
  "dna repair",
  "dna sequencing",
  "driver mutation",
  "driver mutations",
  "ebv dna",
  "ebv-dna",
  "ecdna",
  "ecog",
  "ecog performance status",
  "epigenetic",
  "epigenetics",
  "exo-mirna",
  "expression",
  "fish",
  "fusion",
  "gene expression",
  "gene expression profile",
  "gene fusion",
  "gene mutation",
  "gene panel",
  "gene signature",
  "genomic",
  "genomic alteration",
  "genomic alterations",
  "genomic instability",
  "genomic instability score",
  "genomic landscape",
  "genomic profiling",
  "genomic signature",
  "genomics",
  "germline mutation",
  "germline mutations",
  "hbv dna",
  "hbv-dna",
  "hpv dna",
  "ihc",
  "immunohistochemistry",
  "international staging system stage 3",
  "iss stage 3",
  "karnofsky",
  "kps",
  "line-1 dna",
  "liquid biopsy",
  "metabolomic",
  "metabolomics",
  "methylation",
  "microbiome",
  "mirna",
  "mirnas",
  "molecular",
  "molecular alteration",
  "molecular alterations",
  "molecular classification",
  "molecular profiling",
  "molecular residual disease",
  "molecular subtype",
  "molecular subtypes",
  "molecular subtyping",
  "molecular test",
  "molecular testing",
  "mrd",
  "mrna",
  "mtdna",
  "multi-gene panel",
  "multi-omics",
  "multigene panel",
  "mutant",
  "mutation",
  "mutation burden",
  "mutation status",
  "mutational burden",
  "mutations",
  "negative",
  "next-generation sequencing",
  "ngs",
  "omics",
  "oncosignature",
  "overexpression",
  "panel",
  "pathologic complete response",
  "pcr",
  "pcr (pathologic complete response)",
  "performance status",
  "point mutation",
  "positive",
  "proteomic",
  "proteomics",
  "qpcr",
  "radiomics",
  "rearrangement",
  "rna",
  "rna sequencing",
  "rna-seq",
  "rt-pcr",
  "sequencing",
  "signature",
  "smoking status",
  "somatic mutation",
  "somatic mutations",
  "sphingolipid profiling",
  "stage",
  "status",
  "tme",
  "tnm stage",
  "transcriptomic",
  "transcriptomics",
  "translocation",
  "ttmv-hpv dna",
  "tumor microenvironment",
  "utdna",
  "wes",
  "wgs",
  "whole exome sequencing",
  "whole genome sequencing",
  "wild type",
  "wild-type",
  "wildtype",
])

// 표기 병합: normalizedRaw -> canonical surface
const CANON = {
  "-prame": "PRAME",
  "11q13 amplification": "11q13",
  "18 f-fmiso": "18F-FMISO",
  "1p/19q codeletion": "1p/19q co-deletion",
  "1p19q": "1p/19q",
  "1q amplification": "1q",
  "1q gain/amplification": "1q gain",
  "21-gene recurrence-score": "21-gene recurrence score",
  "2hg": "2-HG",
  "5-hmc": "5hmC",
  "5-mc": "5mC",
  "a2ar expression": "A2aR",
  "adc-trs": "ADC TRS",
  "aldh-1": "ALDH1",
  "alk expression": "ALK",
  "amp 1q": "amp1q",
  "ap-1": "AP1",
  "apc mutations": "APC",
  "ar lbd": "AR-LBD",
  "ar lbd mutations": "AR-LBD",
  "ar mutation": "AR",
  "ar-lbd mutation": "AR-LBD",
  "ar-lbd mutations": "AR-LBD",
  "arg-1": "ARG1",
  "arv7": "AR-V7",
  "ascl-1": "ASCL1",
  "atm mutation": "ATM",
  "b-cell": "B cell",
  "b-cells": "B cells",
  "b-raf": "BRAF",
  "b7h3": "B7-H3",
  "b7h4": "B7-H4",
  "bcells": "B cells",
  "bcl-6": "BCL6",
  "bcl2": "BCL-2",
  "bclxl": "BCL-XL",
  "beclin1": "Beclin-1",
  "beta-2-microglobulin": "beta-2 microglobulin",
  "beta2-microglobulin": "beta-2 microglobulin",
  "braf -v600e": "BRAF V600E",
  "braf mutant": "BRAF",
  "braf mutation": "BRAF",
  "braf mutations": "BRAF",
  "braf-mutant": "BRAF",
  "braf-v600": "BRAF V600",
  "braf-v600e": "BRAF V600E",
  "braf-v600k": "BRAF V600K",
  "brafv600": "BRAF V600",
  "brafv600e": "BRAF V600E",
  "brca 1/2": "BRCA1/2",
  "brca mutation": "BRCA",
  "brca-1": "BRCA1",
  "brca1-2": "BRCA1/2",
  "c-met": "cMET",
  "c-met amplification": "cMET",
  "c-met expression": "cMET",
  "c-met overexpression": "cMET",
  "c-met protein overexpression": "c-Met protein",
  "ca 125": "CA125",
  "ca 15-3": "CA15-3",
  "ca 19-9": "CA19-9",
  "ca 19.9": "CA19.9",
  "ca ix": "CAIX",
  "ca-125": "CA125",
  "ca-15-3": "CA15-3",
  "ca-19-9": "CA19-9",
  "ca-9": "CA9",
  "ca153": "CA15-3",
  "ca199": "CA19-9",
  "ca724": "CA72-4",
  "caspase 3": "Caspase-3",
  "caspase 8": "caspase-8",
  "caspase 9": "caspase-9",
  "caspase3": "Caspase-3",
  "cav1": "Cav-1",
  "ccl-2": "CCL2",
  "ccne1 amplification": "CCNE1",
  "cd-56": "CD56",
  "cd274": "PD-L1",
  "cd4 + t cells": "CD4+ T cells",
  "cd70 ihc": "CD70",
  "cd8 + t cells": "CD8+ T cells",
  "cd8 + t-cell infiltration": "CD8+ T cell infiltration",
  "cd8 t-cells": "CD8 T cells",
  "cd8+ t-cell": "CD8+ T cell",
  "cd8+ t-cell infiltration": "CD8+ T cell infiltration",
  "cd8+ t-cells": "CD8+ T cells",
  "cd8+pd-1+": "CD8+PD1+",
  "cd8+t cell": "CD8+ T cell",
  "cd8+t cell infiltration": "CD8+ T cell infiltration",
  "cd8+t cells": "CD8+ T cells",
  "cd8+tils": "CD8+ TILs",
  "cdh6 expression": "CDH6",
  "cdk4 amplification": "CDK4",
  "cdk4/6 amplification": "CDK4/6",
  "ceacam-5": "CEACAM5",
  "cell-cycle": "cell cycle",
  "cgas/sting": "cGAS-STING",
  "ck5/6": "CK 5/6",
  "ckit": "C-KIT",
  "ckmb": "CK-MB",
  "claudin 18.2": "Claudin18.2",
  "claudin-low": "Claudin Low",
  "cldn 18.2": "CLDN18.2",
  "cldn6 ihc": "CLDN6",
  "cleaved caspase 3": "cleaved caspase-3",
  "cleaved-caspase-3": "cleaved caspase-3",
  "cll1": "CLL-1",
  "cmet expression": "cMET",
  "cmyc": "c-Myc",
  "cox2": "COX-2",
  "csf-1": "CSF1",
  "cthpv dna": "ctHPV-DNA",
  "ctla-4 expression": "CTLA-4",
  "ctla4": "CTLA-4",
  "cxcl-10": "CXCL10",
  "cxcl-9": "CXCL9",
  "cyclind1": "cyclin D1",
  "cyfra21-1": "CYFRA 21-1",
  "cyfra211": "CYFRA 21-1",
  "del 17p": "del17p",
  "dlk-1": "DLK1",
  "dna-repair": "DNA repair mutations",
  "dnam-1": "DNAM1",
  "ebv status": "EBV",
  "ebv-positive": "EBV",
  "ecog-ps": "ECOG PS",
  "egf-r": "EGFR",
  "egfr amplification": "EGFR",
  "egfr exon 20 insertion mutation": "EGFR Exon 20 insertion",
  "egfr exon 20ins": "EGFR exon20ins",
  "egfr exon-20 insertion mutation": "EGFR Exon 20 insertion",
  "egfr exon20 insertion mutations": "EGFR Exon 20 insertion",
  "egfr expression": "EGFR",
  "egfr mutation": "EGFR",
  "egfr mutation status": "EGFR",
  "egfr mutations": "EGFR",
  "egfr overexpression": "EGFR",
  "egfr sensitive": "EGFR-SENSITIVE",
  "egfr sensitive mutation": "EGFR-SENSITIVE",
  "egfr t790m mutation": "EGFR T790M",
  "egfr-mutant": "EGFR",
  "egfr-positive": "EGFR",
  "egfr-sensitizing mutations": "EGFR Sensitizing",
  "egfrmutation": "EGFR",
  "eln2017": "ELN 2017",
  "eno-2": "ENO2",
  "ep-cam": "EpCAM",
  "ep300-mutant": "EP300",
  "epithelial to mesenchymal transition": "epithelial-to-mesenchymal transition",
  "epithelial-mesenchymal transition": "epithelial mesenchymal transition",
  "epstein barr virus": "Epstein-Barr virus",
  "er status": "ER",
  "er-": "ER",
  "er-positive": "ER",
  "erap-1": "ERAP1",
  "erb-b2": "HER2",
  "erbb2": "HER2",
  "erbb2 amplification": "HER2",
  "erbb2 mutation": "HER2",
  "ereg mutations": "EREG",
  "esr1 -mut": "ESR1-mut",
  "esr1 m": "ESR1m",
  "esr1 mutation": "ESR1",
  "esr1 mutations": "ESR1",
  "estrogen receptor status": "estrogen receptor",
  "ezh2 mutations": "EZH2",
  "fdg pet": "FDG-PET",
  "fdg-pet/ct": "FDG PET/CT",
  "fgf-2": "FGF2",
  "fgfr1-3 mutations": "FGFR1-3",
  "fgfr2 amplification": "FGFR2",
  "fgfr2 expression": "FGFR2",
  "fgfr3 mutation": "FGFR3",
  "flt3 itd": "FLT3-ITD",
  "flt3 tkd": "FLT3-TKD",
  "flt3/itd": "FLT3-ITD",
  "folate receptor-alpha": "Folate Receptor Alpha",
  "fox c1": "FOXC1",
  "fr-\u03b1": "FR\u03b1",
  "g brca": "GBRCA",
  "g-h2ax": "gH2AX",
  "g-mdsc": "gMDSC",
  "gal9": "Gal-9",
  "gamma h2ax": "gamma-H2AX",
  "gata-3": "GATA3",
  "gdf15": "GDF-15",
  "globo-h": "Globo H",
  "glu/cer": "GluCer",
  "glut-1": "GLUT1",
  "gmcsf": "GM-CSF",
  "gnas mutation": "GNAS",
  "gpc-1": "GPC1",
  "gpc-3": "GPC3",
  "granzymeb": "Granzyme B",
  "grk2 amplification": "GRK2",
  "h oxb13": "HOXB13",
  "h2-d1": "H2D1",
  "h3 k27m": "H3K27M",
  "h3k27m mutation": "H3K27M",
  "hdl cholesterol": "HDL-cholesterol",
  "her-2": "HER2",
  "her-2 amplification": "HER2",
  "her2 amplification": "HER2",
  "her2 ihc": "HER2",
  "her2 ihc 2+": "HER2",
  "her2 ihc 2+/ish+": "HER2 IHC2+/ISH+",
  "her2 ihc 3+": "HER2",
  "her2 ihc0": "HER2",
  "her2 ihc3+": "HER2",
  "her2 low": "HER2-low",
  "her2 mutation": "HER2",
  "her2 overexpression": "HER2",
  "her2 status": "HER2",
  "her2-": "HER2",
  "her2-amplified": "HER2",
  "her2-ihc": "HER2",
  "her2-low expression": "HER2-low",
  "her2-mutant": "HER2",
  "her2-overexpression": "HER2",
  "her2-positive": "HER2",
  "her2neu": "HER2/neu",
  "her3 ihc": "HER3",
  "hif1": "HIF-1",
  "hif1-\u03b1": "HIF-1\u03b1",
  "hif1\u03b1": "HIF-1\u03b1",
  "hif2\u03b1": "HIF-2\u03b1",
  "hiv status": "HIV",
  "hla a*02-01": "HLA-A*0201",
  "hla class-i": "HLA class I",
  "hla e": "HLA-E",
  "hla i": "HLA-I",
  "hla loh": "HLA-LOH",
  "hla-a * 0201": "HLA-A*0201",
  "hla-a * 02:01": "HLA-A*02:01",
  "hla-class i": "HLA class I",
  "hla_a2": "HLA-A2",
  "hladr+": "HLA-DR+",
  "hmgb-1": "HMGB1",
  "hmox-1": "HMOX1",
  "hormone-receptor": "hormone receptor",
  "hpv 16": "HPV16",
  "hpv 16+": "HPV16+",
  "hpv 18": "HPV18",
  "hpv status": "HPV",
  "hpv-": "HPV",
  "hpv-16": "HPV16",
  "hpv-18": "HPV18",
  "hpv-35": "HPV35",
  "hpv-45": "HPV45",
  "hpv-negative": "HPV",
  "hpv-negative status": "HPV",
  "hpv-positive": "HPV",
  "hr-": "HR",
  "hrd-positive": "HRD",
  "hrd-sum": "HRDsum",
  "hrhpv": "HR-HPV",
  "hscore": "H-score",
  "hscrp": "hs-CRP",
  "iba-1": "Iba1",
  "icam-1": "ICAM1",
  "idh mutation": "IDH",
  "idh status": "IDH",
  "idh wt": "IDHwt",
  "idh-1": "IDH1",
  "idh-mutant": "IDH",
  "idh-wt": "IDHwt",
  "idh1 mutation": "IDH1",
  "idh1 r132h": "IDH1-R132H",
  "ido-1": "IDO1",
  "ifn gamma": "IFN-gamma",
  "ifn-": "IFN",
  "ifn-a": "IFNA",
  "ifn-g": "IFNG",
  "ifn-y": "IFNy",
  "ifn\u03b1": "IFN-\u03b1",
  "ifn\u03b2": "IFN-\u03b2",
  "ifn\u03b3": "IFN-\u03b3",
  "igf-1r": "IGF1R",
  "igf1": "IGF-1",
  "igf2": "IGF-2",
  "igfbp-1": "IGFBP1",
  "igfbp-2": "IGFBP2",
  "igfbp-3": "IGFBP3",
  "igfbp-7": "IGFBP7",
  "ighv mutation": "IGHV",
  "ighv mutation status": "IGHV",
  "igsf8 membrane protein expression": "IGSF8 membrane protein",
  "ihc 1+": "IHC 2+",
  "ihc 3+": "IHC 2+",
  "ihc90+": "IHC 2+",
  "il-12b": "IL12B",
  "il-13": "IL13",
  "il-13r": "IL13R",
  "il-1b": "IL1B",
  "il-1r1": "Il1r1",
  "il-33": "IL33",
  "il-4r": "IL4R",
  "il-7": "IL7",
  "il-7r": "IL7R",
  "il1-r1": "Il1r1",
  "il10": "IL-10",
  "il12": "IL-12",
  "il15": "IL-15",
  "il17": "IL-17",
  "il17a": "IL-17A",
  "il18": "IL-18",
  "il1\u03b2": "IL-1\u03b2",
  "il2": "IL-2",
  "il21": "IL-21",
  "il27": "IL-27",
  "il2r": "IL-2R",
  "il4": "IL-4",
  "il6": "IL-6",
  "il6r": "IL-6R",
  "il8": "IL-8",
  "interferon-gamma": "interferon gamma",
  "interleukin 6": "interleukin-6",
  "ip 10": "IP-10",
  "ip10": "IP-10",
  "jak/stat": "JAK-STAT",
  "jak2v617f": "JAK2 V617F",
  "k-ras": "KRAS",
  "keratin 19": "Keratin19",
  "ki-67": "Ki67",
  "kit exon 11 mutation": "KIT exon 11",
  "kit exon 11 mutations": "KIT exon 11",
  "kit mutation status": "KIT",
  "klrg-1": "KLRG1",
  "kras amplification": "KRAS",
  "kras g12c mutation": "KRAS G12C",
  "kras mt": "KRAS-MT",
  "kras mutation": "KRAS",
  "kras mutation status": "KRAS",
  "kras mutations": "KRAS",
  "kras p.g12c mutation": "KRAS p.G12C",
  "kras-g12c": "KRAS G12C",
  "kras-g12d": "KRAS G12D",
  "kras-g12v": "KRAS G12V",
  "kras-mutant": "KRAS",
  "krasg12": "KRAS G12",
  "krasg12c": "KRAS G12C",
  "krasg12d": "KRAS G12D",
  "krasg12r": "KRAS G12R",
  "krasg12v": "KRAS G12V",
  "krasmt": "KRAS-MT",
  "l858r mutation": "L858R",
  "lag-3": "LAG3",
  "lage1a": "LAGE-1A",
  "ldh-a": "LDHA",
  "lewis y": "LEWIS-Y",
  "line1": "LINE-1",
  "lmp-1": "LMP1",
  "lymph node": "lymph node status",
  "m2-macrophages": "M2 macrophages",
  "mage-a1": "MAGEA1",
  "mage-a4 expression": "MAGE-A4",
  "magea3": "MAGE-A3",
  "magea4": "MAGE-A4",
  "mapk mutations": "MAPK",
  "mapk pathway mutations": "MAPK pathway",
  "mart1": "MART-1",
  "mat-2a": "MAT2A",
  "mcl-1": "MCL1",
  "mcl1 amplification": "MCL1",
  "mcp1": "MCP-1",
  "mcp3": "MCP-3",
  "mcp4": "MCP-4",
  "mdm-2": "MDM2",
  "mdm2 amplification": "MDM2",
  "mdm2 expression": "MDM2",
  "mdm2-amplified": "MDM2",
  "mdr-1": "MDR1",
  "mek1 mutations": "MEK1",
  "met amp": "METamp",
  "met amplification": "MET",
  "met ex14": "METex14",
  "met ex14 skipping": "METex14 skipping",
  "met ex14skipping": "METex14 skipping",
  "met exon 14 skipping mutation": "MET exon 14 skipping",
  "met exon 14 skipping mutations": "MET exon 14 skipping",
  "met exon 14skipping": "MET exon 14 skipping",
  "met exon14 skipping": "MET exon 14 skipping",
  "met ihc": "MET",
  "met overexpression": "MET",
  "met-amp": "METamp",
  "met-amplified": "MET",
  "met-overexpression": "MET",
  "metex14 skipping mutations": "METex14 skipping",
  "mgmt promoter status": "MGMT promoter",
  "mgmtpromoter methylation": "MGMT promoter methylation",
  "mhc i": "MHC-I",
  "mhc ii": "MHC-II",
  "mhc-1": "Mhc1",
  "mhc_1": "Mhc1",
  "mhcii": "MHC-II",
  "mib-1": "MIB1",
  "microsatellite instability": "MSI-H",
  "microsatellite instability high": "MSI-H",
  "microsatellite instability-high": "MSI-H",
  "microsatellite-instability": "MSI-H",
  "microsatellite-stable": "microsatellite stable",
  "mir155": "miR-155",
  "mir16": "miR-16",
  "mir21": "miR-21",
  "mir375": "miR-375",
  "mismatch repair status": "mismatch repair",
  "mismatch repair-deficient": "mismatch repair deficient",
  "mmdsc": "M-MDSC",
  "mmdscs": "M-MDSCs",
  "mmp 2": "MMP2",
  "mmp 9": "MMP-9",
  "mmp-1": "MMP1",
  "mmp-10": "MMP10",
  "mmp-2": "MMP2",
  "mmp-3": "MMP3",
  "mmp-7": "MMP7",
  "mmp9": "MMP-9",
  "mmr status": "MMR",
  "mmr-d": "MMRd",
  "mmr-p": "MMRp",
  "msi": "MSI-H",
  "msi high": "MSI-H",
  "msi stable": "MSI-STABLE",
  "msi-h": "MSI-H",
  "msi-high": "MSI-H",
  "msih": "MSI-H",
  "mtap mutations": "MTAP",
  "mtapdel": "MTAP-del",
  "mtor mutation": "mTOR",
  "muc-1": "MUC1",
  "muc-16": "MUC16",
  "mx-1": "Mx1",
  "myb overexpression": "MYB",
  "myd-88": "MYD88",
  "myeloid-derived suppressor cells": "myeloid derived suppressor cells",
  "n-stage": "N stage",
  "ncam-1": "NCAM1",
  "ne status": "NE",
  "nectin-4 ihc": "NECTIN-4",
  "nectin4": "NECTIN-4",
  "nectin4 amplification": "NECTIN-4",
  "neo-antigen": "neoantigen",
  "neo-antigens": "neoantigens",
  "neutrophil to lymphocyte ratio": "neutrophil-to-lymphocyte ratio",
  "neutrophil-lymphocyte-ratio": "neutrophil-lymphocyte ratio",
  "neutrophil/lymphocyte ratio": "neutrophil-lymphocyte ratio",
  "nf-1": "NF1",
  "nf-l": "NfL",
  "nf2 mutations": "NF2",
  "nfkb": "NF-kB",
  "nf\u03bab": "NF-\u03baB",
  "nlrp-3": "NLRP3",
  "notch 1": "NOTCH1",
  "notch 3": "NOTCH3",
  "npm1 mutation": "NPM1",
  "nras mutation": "NRAS",
  "nras-mutant": "NRAS",
  "nrf-2": "NRF2",
  "nrg-1": "NRG1",
  "nrp-1": "NRP1",
  "nt-pro-bnp": "NT-proBNP",
  "ntprobnp": "NT-proBNP",
  "ntrk 1-3": "NTRK1-3",
  "nyeso1": "NY-ESO-1",
  "o 6 -methylguanine dna methyltransferase": "O6-methylguanine-DNA methyltransferase",
  "o6-methylguanine dna methyltransferase": "O6-methylguanine-DNA methyltransferase",
  "oct 4": "OCT4",
  "oct-4": "OCT4",
  "oncotypedx": "Oncotype DX",
  "ox-40": "OX40",
  "p-akt": "pAKT",
  "p-erk": "PERK",
  "p-s6": "pS6",
  "p-stat3": "pSTAT3",
  "p16 ink4a": "p16INK4a",
  "p16 positive": "p16",
  "p53": "TP53",
  "p53 mutation": "TP53",
  "pai1": "PAI-1",
  "pan ck": "PanCK",
  "pan-ck": "PanCK",
  "parp inhibitor status": "PARP inhibitor",
  "parp-1": "PARP1",
  "parp-1 ihc": "PARP1",
  "pchk1": "p-Chk1",
  "pd(l)-1": "PD-(L)1",
  "pd(l)1": "PD-(L)1",
  "pd-1 expression": "PD-1",
  "pd-l1 expression": "PD-L1",
  "pd-l1 ihc": "PD-L1",
  "pd-l1 negative": "PD-L1",
  "pd-l1 positive": "PD-L1",
  "pd-l1 status": "PD-L1",
  "pd1": "PD-1",
  "pd1+": "PD-1+",
  "pd1-pdl1": "PD-1/PD-L1",
  "pd1/pd-l1": "PD-1/PD-L1",
  "pdcd1": "PD-1",
  "pdgf-b": "PDGFB",
  "pdgfr-\u03b2": "PDGFR\u03b2",
  "pdgfra-mutant": "PDGFRA",
  "pdl-1": "PD-L1",
  "pdl-1 cps": "PD-L1 CPS",
  "pdl-2": "PD-L2",
  "pdl1": "PD-L1",
  "pdl1 tps": "PD-L1 TPS",
  "pdl2": "PD-L2",
  "perk1/2": "p-ERK1/2",
  "pet-ct": "PET/CT",
  "philadelphia-chromosome": "Philadelphia Chromosome",
  "pi-3k/akt": "PI3K/AKT",
  "pi3k-akt": "PI3K/AKT",
  "pi3k/akt/mtor": "PI3K-AKT-mTOR",
  "pi3k/akt/mtor pathway": "PI3K-Akt-mTOR pathway",
  "pi3k/akt/mtor pathway mutations": "PI3K-Akt-mTOR pathway",
  "pi3kca mutation": "PI3KCA",
  "pik3ca mutation": "PIK3CA",
  "pik3ca mutations": "PIK3CA",
  "pik3cah1047r": "PIK3CA H1047R",
  "platinum-sensitivity": "platinum sensitivity",
  "pole mut": "POLEmut",
  "pro-grp": "ProGRP",
  "protein expression": "protein",
  "psma pet-positive": "PSMA PET",
  "psma-expression": "PSMA",
  "psma-pet": "PSMA PET",
  "psmad2": "P-SMAD2",
  "pten mutations": "PTEN",
  "raf1 amplification": "RAF1",
  "ras mutation": "RAS",
  "ras mutation status": "RAS",
  "ras wt": "RAS-WT",
  "ras-mutant": "RAS",
  "ras/mapk": "RAS-MAPK",
  "rasmut": "RAS mut",
  "rd3 expression": "RD3",
  "regulatory t-cells": "regulatory T cells",
  "ret-fusion": "RET fusion",
  "ros-1": "ROS1",
  "rtk-ras": "RTK/RAS",
  "sa\u03b2gal": "SA-\u03b2-gal",
  "sdf1": "SDF-1",
  "sdh-b": "SDHB",
  "serpin a3": "SERPINA3",
  "serpin-e1": "SERPINE1",
  "siglec-10": "SIGLEC10",
  "sil-2r": "sIL2R",
  "sirp-a": "Sirpa",
  "smarca4 negative ihc": "SMARCA4",
  "sox 2": "SOX2",
  "spd1": "sPD-1",
  "steap1 protein expression": "STEAP1 protein",
  "sting expression": "STING",
  "stnf-r2": "sTNFR2",
  "suv max": "SUVmax",
  "t cell activation": "T-cell activation",
  "t regs": "Tregs",
  "t regulatory cells": "T-regulatory cells",
  "t-bet": "Tbet",
  "t-cell": "T cell",
  "t-cell activation markers": "T cell activation markers",
  "t-cell activation status": "T-cell activation",
  "t-cell infiltration": "T cell infiltration",
  "t-cells": "T cells",
  "t-eff": "Teff",
  "t-regs": "Tregs",
  "t315i mutation": "T315I",
  "t790m mutation": "T790M",
  "ta-repeat expansions": "TA repeat expansions",
  "tcell inf gep": "TcellinfGEP",
  "tcells": "T cells",
  "tcf-1": "TCF1",
  "tcf1 + stem-like cd8 + t cells": "TCF1+ stem-like CD8+ T cells",
  "tenascin c": "TENASCIN-C",
  "tert promoter mutation": "TERT promoter",
  "tert promoter mutations": "TERT promoter",
  "tert-promoter": "TERT promoter",
  "tet-2": "TET2",
  "tgf \u03b2": "TGF-\u03b2",
  "tgf \u03b2 1": "TGF\u03b21",
  "tgf-b": "TGFb",
  "tgf-b1": "TGFB1",
  "tgf-\u03b21": "TGF\u03b21",
  "tgf-\u03b22": "TGF\u03b22",
  "tgf\u03b2": "TGF-\u03b2",
  "th-17": "Th17",
  "tie-2": "TIE2",
  "tim-3": "TIM3",
  "timp-1": "TIMP1",
  "tmb h": "TMB-H",
  "tmb high": "TMB-high",
  "tnf-alpha": "TNF alpha",
  "tnfa": "TNF-a",
  "tnfalpha": "TNF alpha",
  "tnf\u03b1": "TNF-\u03b1",
  "top1 mutations": "TOP1",
  "tp-53": "TP53",
  "tp53 mutation": "TP53",
  "tp53 mutations": "TP53",
  "tp53-/-": "TP53",
  "tp53mut": "TP53 mut",
  "trail r2": "TRAIL-R2",
  "triple": "triple-negative",
  "triple negative": "triple-negative",
  "triple-negative breast cancer": "Triple Negative Breast Cancer",
  "trop-2": "TROP2",
  "trop1": "TROP-1",
  "tsp1": "TSP-1",
  "ttf1": "TTF-1",
  "tumor infiltrating lymphocytes": "tumor-infiltrating lymphocytes",
  "tumor-fraction": "tumor fraction",
  "vcam-1": "VCAM1",
  "vegf-a": "VEGFA",
  "vegf-d": "VEGFD",
  "vegfb": "VEGF-B",
  "vegfc": "VEGF-C",
  "vegfr-2": "VEGFR2",
  "vegfr3": "VEGFR-3",
  "wee-1": "WEE1",
  "wt-1": "WT1",
  "xct-": "xCT",
  "yap-1": "YAP1",
  "ykl40": "YKL-40",
  "\u03b1-sma": "\u03b1SMA",
  "\u03b3-h2ax": "\u03b3H2AX",
  "\u03b3\u03b4 t-cells": "\u03b3\u03b4 T cells",
}

// 원소 배열을 정제·정규화·중복제거해서 반환 (dataSource 에서 각 레코드 biomarker_list 에 적용)
export function cleanBiomarkers(list) {
  if (!list || !list.length) return list || []
  const out = []
  const seen = new Set()
  for (const b of list) {
    const nb = norm(b)
    if (!nb || BLOCK.has(nb)) continue
    const c = CANON[nb] ?? (typeof b === 'string' ? b.trim() : b)
    const nc = norm(c)
    if (seen.has(nc)) continue
    seen.add(nc)
    out.push(c)
  }
  return out
}
